//arquivos fontes do jogo
var g_resources = [{
    name: "area01_fase_tiles-nq8",
    type: "image",
    src: "data/area01_tileset/area01_fase_tiles-nq8.png"
}, {
    name: "area01_fase_placa_infogelo",
    type: "image",
    src: "data/area01_tileset/area01_fase_placa_infogelo-nq8.png"
}, {
    name: "area01_fase_placa_infogelo",
    type: "image",
    src: "data/area01_tileset/area01_fase_placa_infogelo-nq8.png"
}, {
    name: "menu_principal",
    type: "image",
    src: "data/GUI/menu_principal.png"
}, {
    name: "cerebro-nq8",
    type: "image",
    src: "data/sprite/cerebro-nq8.png"
}, {
    name: "menu_fim",
    type: "image",
    src: "data/GUI/menu_fim.png"
}, {
    name: "area01",
    type: "tmx",
    src: "data/area01.tmx"
}, {
    name: "sprite_tux-nq8",
    type: "image",
    src: "data/sprite/sprite_tux-nq8.png"
}, {
    name: "sprite_tuxie-nq8",
    type: "image",
    src: "data/sprite/sprite_tuxie-nq8.png"
}, {
    name: "area01_fundo0-nq8",
    type: "image",
    src: "data/area01_parallax/area01_fundo0-nq8.png"
}, {    
    name: "area01_fundo1-nq8",
    type: "image",
    src: "data/area01_parallax/area01_fundo1-nq8.png"
}, {
    name: "sprite_moeda_ubuntu-nq8",
    type: "image",
    src: "data/sprite/sprite_moeda_ubuntu-nq8.png"
}, {
    name: "sprite_moeda_fedora-nq8",
    type: "image",
    src: "data/sprite/sprite_moeda_fedora-nq8.png"
}, {
    name: "sprite_moeda_debian-nq8",
    type: "image",
    src: "data/sprite/sprite_moeda_debian-nq8.png"
}, {
    name: "sistema_pera-nq8",
    type: "image",
    src: "data/sprite/sistema_pera-nq8.png"
}, {
    name: "kromasky_16x16",
    type: "image",
    src: "data/sprite/kromasky_16x16.png"
}, {
    name: "btnleft",
    type: "image",
    src: "data/sprite/btnleft.png"
},{
    name: "btnright",
    type: "image",
    src: "data/sprite/btnright.png"
},{
    name: "btnjump",
    type: "image",
    src: "data/sprite/btnjump.png"
}, {
    name: "pulo",
    type: "audio",
    src: "data/audio/",
    channel: 1
}, {
    name: "moeda",
    type: "audio",
    src: "data/audio/",
    channel: 1
}, {
    name: "intro",
    type: "audio",
    src: "data/audio/",
    channel: 1
}, {
    name: "heavy",
    type: "audio",
    src: "data/audio/",
    channel: 1
}, {
    name: "soundtrack_level1",
    type: "audio",
    src: "data/audio/",
    channel: 1
}];  
